language: go
go:
  - 1.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-utils
script:
  - xmllint --noout --schema ./static/level.xsd ./static/levels/*.lvl
  - go test ./...
notifications:
  email: false